# Generated by Django 5.2.5 on 2025-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
