# Generated by Django 5.2.5 on 2025-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriebalance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedfood',
            name='calories_consumed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
