# Generated by Django 5.2.5 on 2025-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriebalance', '0002_loggedfood_calories_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='last_tracked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='time_tracked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loggedfood',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
