# Generated by Django 5.2.5 on 2025-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriebalance', '0003_food_last_tracked_food_time_tracked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='brand',
        ),
        migrations.AddField(
            model_name='food',
            name='usda_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
